platform :ios, '8.0'

use_frameworks!
inhibit_all_warnings!

def shared_pods
  pod 'FolioReaderKit', path: '../'
end

def testing_pods
  pod 'Quick', '0.10.0'
  pod 'Nimble', '~> 5.0.0' 
end

target 'Example' do
  shared_pods
end

target 'StoryboardExample' do
	shared_pods
end

target 'FolioReaderTests' do
  shared_pods
  testing_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
